### ISSUE TITLE
About information extraction

### ISSUE THREAD

**Issue by syw1996** [ZhitingHu/text_content_manipulation#1]
When I want to calculate the precision and recall of my model, I have trouble in using the codes provided by harvardnlp (data2text), since the data structure of data2text code is document level (but your data structure is sentence level). If it's convenient, can you provide your information extraction code which is used to extract the tuple from pred y?

**Comment by zmskye** [comment]
Hi，I'm a student from ustc, do you have the code about this paper "Toward Unsupervised Text Content Manipulation", could you please give me this code, I'm very interested in this paper. Thanks sincerely. @syw1996

**Comment by ha-lins** [comment]
Hi @zmskye , our code for the project has been released at this [repo](https://github.com/ha-lins/DTG-SI). And the data has been extended [here](https://github.com/ha-lins/DTG-SI-data).
